---
# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
#
# YAML format reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema
#
#

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  goRootDir: '/usr/local'
  TargetGoVersion: 1.12.4

steps:
  # download Go, make sure that GOBIN and GOROOT/bin are inserted at the
  # beginning of the PATH
  - bash: |
      cd /tmp
      wget --quiet --output-document go.linux-amd64.tar.gz "https://golang.org/dl/go$(TargetGoVersion).linux-amd64.tar.gz"
      sudo tar --directory '$(goRootDir)' -xzf go.linux-amd64.tar.gz
      GOBIN="$HOME/go/bin"
      echo "##vso[task.setvariable variable=GOBIN]${GOBIN}"
      echo "##vso[task.prependpath]${GOBIN}"
      echo "##vso[task.prependpath]$(goRootDir)/go/bin"
    displayName: 'Download Go'

  - script: |
      go version
      go env
      echo "path: $PATH"
    displayName: 'Check Go version'

  - script: |
      go test -mod=vendor ./...
    displayName: 'Run the tests'
