---
# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
#
# YAML format reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema
#
#

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOROOT: '/usr/local/go'
  GOBIN: '$(system.defaultWorkingDirectory)/../bin'
  TargetGoVersion: 1.12.4

steps:
  # checkout the repo as a shallow copy
  - checkout: self
    clean: true
    fetchDepth: 1

  # download Go, make sure that GOBIN and GOROOT/bin are inserted at the
  # beginning of the PATH
  - bash: |
      cd /tmp
      wget -O go.linux-amd64.tar.gz "https://golang.org/dl/go$(TargetGoVersion).linux-amd64.tar.gz"
      sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Download Go'

  - script: |
      go version
      go env
    displayName: 'Check Go version'

  - script: |
      go test -mod=vendor ./...
    displayName: 'Run the tests'
